---
- include: zsh.yml
- include: snap.yml
# - include: dot-files.yml

- name: Install Utils
  pacman:
    name: '{{ utils }}'
    state: present
  become: yes

- name: Install Utils from Arch User Repository
  script: ../../../scripts/install-aur.sh {{ item }}
  with_items: '{{ utils_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur

- name: Custom Fonts
  package:
    name: ['ttf-fira-code', 'ttf-jetbrains-mono']
    state: present
  become: true

- name: CLI Utils
  package:
    name: ['ripgrep', 'tmux', 'inotify-tools', 'htop', 'pass']
    state: present
  become: true

- name: Creates Workspace directory
  file:
    path: /home/{{ user_name }}/workspace
    state: directory
  become_user: '{{ user_name }}'
  become: yes
