---
- name: Install Base packages
  include_tasks: ../../install_packages_template.yml
  vars:
    tag: base
    packages: base
    packages_distro: base_distro
    packages_snap: base_snap
    packages_yay: base_yay
