---
# yay is required on top of this file in order to be used for installing AUR packages
- include: yay.yml
  when: ansible_distribution == 'Archlinux'

- name: Install Base packages
  package:
    name: '{{ base }}'
    state: present
  become: yes
  tags:
    - base

- name: Install Base packages from AUR
  script: ../../../scripts/install-aur.sh {{ item }}
  with_items: '{{ base_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  when: ansible_distribution == 'Archlinux'
  tags:
    - aur
    - base
