---
- name: Update apt-get repo and cache (apt-get update)
  apt:
    update_cache: yes
    force_apt_get: yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  tags:
    - base

- name: Update cache and the whole system (pacman -Syu)
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == 'Archlinux'
  become: yes
  tags:
    - base

- name: Install Base packages
  include_tasks: ../../install_packages_template.yml
  tags:
    - base

- name: Install Yay Aur (Archlinux only)
  include_tasks: yay.yml
  when: ansible_distribution == 'Archlinux'
  tags:
    - base

- name: Include Asdf for installing essential package managers (npm, yarn)
  include_tasks: asdf.yml
  vars:
    # TODO not the ideal solution, but this helps asdf tasks to understand that asdf is in the path
    asdf_path: '{{ home_dir }}/.asdf/shims:{{ home_dir }}/.asdf/bin:{{ ansible_env.PATH }}'
  tags:
    - base
