---
- name: Installing Zsh
  package:
    name: zsh
    state: present
  become_user: '{{ user_name }}'
  become: yes

- name: Install Oh My Zsh
  script: ../files/install-oh-my-zsh.sh {{ user_name }}
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - zsh

- name: Install Powerlevel10k Theme
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: '/home/{{ user_name }}/powerlevel10k'
    depth: '1'
  tags: zsh

- name: Install Oh My Zsh Plugins
  git:
    repo: '{{ item }}'
    dest: '/home/{{ user_name }}/.oh-my-zsh/custom/plugins/{{ item.split("/") | last }}'
  with_items: '{{ base_omzsh_plugins }}'
  tags: zsh

- name: Set Zsh as default shell
  user:
    name: '{{ user_name }}'
    shell: /usr/bin/zsh
  become: true
  tags:
    - zsh
