---
- name: Install editors
  package:
    name: '{{ editors }}'
    state: present
  become: yes
  tags:
    - editors

- name: Install editors from Distro Package Manager
  script: ../../../scripts/{{ ansible_distribution }}_install.sh {{ item }}
  with_items: '{{ editors_distro }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - distro
    - base
