---
- name: Install editors
  package:
    name: '{{ editors }}'
    state: present
  become: yes
  tags:
    - editors

- name: Install editors from Arch User Repository
  script: ../../../scripts/install-aur.sh {{ item }}
  with_items: '{{ editors_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  when: ansible_distribution == 'Archlinux'
  tags:
    - aur
    - editors
