#!/bin/bash

os=$(uname -a)

if [[ "$os" == *"Ubuntu"* ]]; then
  echo "DISTRO: UBUNTU"

  # sudo apt install curl git

  # git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  # cd ~/.asdf
  # git checkout "$(git describe --abbrev=0 --tags)"

  echo "Updating the system..."
  sudo apt update

  echo "Installing ansible..."
  sudo apt update
  sudo apt install software-properties-common
  sudo apt-add-repository --yes --update ppa:ansible/ansible
  sudo apt install ansible

  # echo "Installing neovim..."
  # sudo apt install neovim

  # echo "Installing tmux..."
  # sudo apt install tmux

  # echo "Installing tmuxinator..."
  # gem install tmuxinator

elif [[ "$os" == *"MANJARO"* ]]; then
  echo "DISTRO: MANJARO"

  echo "Updating the system..."
  sudo pacman -Syy

  echo "Installing ansible..."
  sudo pacman -S ansible --noconfirm

  echo "Provisioning the workstation with Ansible..."
  ansible-playbook ./ansible/local.yml --ask-become-pass

else
  echo "Distro not configured: $os"
fi

# if command -v nvim >/dev/null 2>&1; then
#   echo "Bootstraping Neovim..."
#   nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
# fi
