---
- name: 'Adding user to docker group'
  user:
    name: '{{ user_name }}'
    group: docker
    append: yes
  become: true
  ignore_errors: yes
  tags:
    - development
    - docker

- name: Ensure docker is up
  service:
    name: docker.service
    state: started
    enabled: yes
  become: yes
