---
- name: Install Development packages
  include_tasks: ../../install_packages_template.yml
  vars:
    tag: development
    packages: development_apps
    packages_distro: development_apps_distro
    packages_snap: development_snap
    packages_yay: development_yay

- name: Creates Workspace directory
  file:
    path: /home/{{ user_name }}/workspace
    state: directory
  become_user: '{{ user_name }}'
  tags:
    - development

- include: docker.yml
- include: git.yml
- include: vscode.yml
