---
- name: Creates Workspace directory
  file:
    path: /home/{{ user_name }}/workspace
    state: directory
  become_user: '{{ user_name }}'
  tags:
    - development
    - workspace

- name: Install Development Apps
  package:
    name: '{{ development_apps }}'
    state: present
  become: true
  tags:
    - development

- name: Install Development Apps packages from AUR
  script: ../../../scripts/install-aur.sh {{ item }}
  with_items: '{{ development_apps_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  when: ansible_distribution == 'Archlinux'
  tags:
    - aur
    - development

- include: asdf.yml
- include: docker.yml
- include: git.yml
