---
- include_vars: /home/{{ user_name }}/ansible-local-vars.yml

- name: Generate SSH Keys based on Git Identities
  shell: 'ssh-keygen -t ed25519 -C "{{ item }}" -f /home/{{ user_name }}/.ssh/{{ item.id }}_id_ed25519 -q -N ""'
  with_items: '{{ git.identities }}'

- name: Install Development Apps
  package:
    name: '{{ development_apps }}'
    state: present
  become: true
  tags:
    - development
    - apps

- name: Install Development Apps packages from AUR
  script: ../../../scripts/install-aur.sh {{ item }}
  with_items: '{{ development_apps_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur
    - development

- name: Build .gitconfig from Template
  template:
    src: files/gitconfig.j2
    dest: /home/{{ user_name }}/.gitconfig
  tags:
    - development
    - git

- include: asdf.yml
- include: docker.yml
