---
# TODO check two possibilities:
# 1. use pre_tasks instead of these weird "required packages" convention
# 2. split base role even more to make it as dependency for any other role with just the essential
- name: Install required packages before any other stuff
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ required_packages | default([]) }}'
  become: yes
  when: required_packages is defined

- name: Add APT repos (Ubuntu only)
  apt_repository:
    repo: '{{ item }}'
  with_items: '{{ apt_repos }}'
  when: ansible_distribution == 'Ubuntu' and apt_repos is defined

- name: Install cross distro packages from standard package manager
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ packages_cross | default([]) }}'
  become: yes
  when: packages_cross is defined

- name: Install Archlinux packages from standard package manager
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ packages_Archlinux }}'
  become: yes
  when: ansible_distribution == 'Archlinux' and packages_Archlinux is defined

- name: Install Ubuntu packages from standard package manager
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ packages_Ubuntu }}'
  become: yes
  when: ansible_distribution == 'Ubuntu' and packages_Ubuntu is defined

- name: Install packages from Yay AUR Helper (Archlinux only)
  yay:
    name: '{{ packages_yay }}'
    state: present
  when: ansible_distribution == 'Archlinux' and packages_yay is defined

- name: Install global packages from Yarn Package
  yarn:
    name: '{{ packages_yarn }}'
    global: yes
    state: present
  when: packages_yarn is defined
