---
- name: Install Browsers packages
  include_tasks: ../../install_packages_template.yml
  vars:
    tag: browsers
    packages: browsers
    packages_distro: browsers_distro
    packages_snap: browsers_snap
    packages_yay: browsers_yay
