---
- name: Install Communication packages
  package:
    name: '{{ browsers }}'
    state: present
  become: yes
  tags:
    - browser

- name: Install browser apps from Distro Package Manager
  script: ../../../scripts/{{ ansible_distribution }}_install.sh {{ item }}
  with_items: '{{ browsers_distro }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  when: browsers_distro is defined
  tags:
    - distro
    - browser
