---
- name: Install browsers from Arch User Repository
  shell: 'yay -S {{ item }} --noconfirm'
  with_items: '{{ browsers_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur
    - browsers
