---
- name: Install Oh My Tmux
  get_url:
    url: 'https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf'
    dest: '/home/{{ user_name }}'
  tags:
    - base
    - tmux

- name: Install Tmux Plugin Manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '/home/{{ user_name }}/.tmux/plugins/tpm'
    force: yes
    depth: '1'
  tags:
    - base
    - tmux

- name: Reload Tmux configuration
  shell: 'tmux source-file /home/{{ user_name }}/.tmux.conf'
  ignore_errors: yes
