---
- name: Install Network Apps
  package:
    name: '{{ item }}'
    state: present
  with_together:
    - '{{ network }}'
    - '{{ network_distro }}'
  become: true
  tags:
    - network

- include: samba.yml
  when: samba is defined

- include: ssh.yml
