# this file is an example of how to customize sensitive host informations
# it must be copied to the user home folder with the proper values and renamed to "ansible-local-vars.yml"
# this one shall not be versioned!

# this must be defined if you want to have an external drive configured in your fstab definition
# otherwise, just get rid of it.
external_drive:
  mount_point: /mnt/mount_point_path
  uuid: 299125EC42BEE838
  fstype: ntfs|ext4|...

# this will be used to create the .gitconfig file and its corresponding keys to connect git via ssh
git:
  name: William Adama
  identities:
    # this is your personal git identity
    - id: personal
      email: williamadama@uol.com
    # and this one is your secondary account (if you have so)
    - id: gallactica
      email: williamadama@bsg.com

# this must be defined if you want to have plex installed in your host
# otherwise, just get rid of it.
plex:
  path: /var/lib/plex/Plex Media Server

# this must be defined if you want to have custom network sharings using samba service
samba:
  sharings:
    - id: sharing-id
      path: /mnt/sharing-folder
      writeable: yes|no
      guest_ok: yes|no
      create_mask: 0777
      directory_mask: 0777
      force_user: linux_user

# this must be defined if you want to have transmission installed in your host
# otherwise, just get rid of it.
transmission:
  download_dir: /mnt/download_dir
  username: username
  password: password
  whitelist: 192.168.1.46
