---
- hosts: localhost
  vars_prompt:
    - name: user_name
      prompt: 'username'
      private: no

  vars_files:
    - 'vars/{{ ansible_distribution }}.yml'
    - '/home/{{ user_name }}/ansible-local-vars.yml'

  roles:
    - { role: base, tags: ['base'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: communication, tags: ['communication'] }
    - { role: development, tags: ['development'] }
    - { role: editors, tags: ['editors'] }
    - { role: multimedia, tags: ['multimedia'] }
    - { role: network, tags: ['network'] }
