---
- hosts: localhost
  vars_prompt:
    - name: user_name
      prompt: 'SO Username'
      private: no

  roles:
    - { role: base, tags: ['base'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: communication, tags: ['communication'] }
    - { role: development, tags: ['development'] }
    - { role: editors, tags: ['editors'] }
    - { role: multimedia, tags: ['multimedia'] }
