- name: Create directory
  file:
    path: '{{ external_drive.mount_point }}'
    state: directory
  become: yes

- name: Mount External Drive
  mount:
    path: '{{ external_drive.mount_point }}'
    src: UUID={{ external_drive.uuid }}
    fstype: '{{ external_drive.fstype }}'
    opts: defaults,nofail 0 0
    state: mounted
  become: yes
  ignore_errors: yes
