---
- name: Install Multimedia Apps
  package:
    name: '{{ multimedia_apps }}'
    state: present
  become: yes
  tags:
    - multimedia
    - apps

- name: Install Multimedia Fonts
  package:
    name: '{{ multimedia_fonts }}'
    state: present
  become: yes
  tags:
    - multimedia
    - fonts

- name: Install Multimedia TTF Fonts from Url
  get_url:
    url: '{{ item }}'
    dest: '/usr/share/fonts/TTF'
    mode: '600'
  with_items: '{{ multimedia_fonts_url }}'
  tags:
    - git
    - multimedia
    - fonts
