---
- name: Install Multimedia Apps
  package:
    name: '{{ multimedia_apps }}'
    state: present
  become: yes
  tags:
    - multimedia
    - apps

- name: Install Multimedia Apps packages from Distro Package Manager
  script: ../../../scripts/{{ ansible_distribution }}_install.sh {{ item }}
  with_items: '{{ multimedia_apps_distro }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - distro
    - multimedia

- name: Install Multimedia Fonts
  block:
    - name: Install fonts from package manager
      package:
        name: '{{ multimedia_fonts }}'
        state: present
      become: yes

    - name: Create destination path for manual installation of fonts
      file:
        path: '/home/{{ user_name }}/.local/share/fonts'
        state: directory

    - name: Download and manual install fonts
      get_url:
        url: '{{ item }}'
        dest: '/home/{{ user_name }}/.local/share/fonts'
        mode: '600'
      with_items: '{{ multimedia_fonts_url }}'
  when: multimedia_fonts is defined
  tags:
    - multimedia
    - fonts

- include: external-drive.yml
  when: external_drive.uuid is defined

- include: plexmediaserver.yml
  when: plex.path is defined

- include: transmission.yml
  when: transmission.download_dir is defined
