- name: Install plexmediaserver from AUR
  script: ../../../scripts/install-aur.sh plex-media-server
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur
    - multimedia
    - plexmediaserver
  when: plex.install | default('false') | bool

- name: Ensure plexmediaserver is up
  service:
    name: plexmediaserver.service
    state: started
    enabled: yes
  become: yes

# still need to store preconfigured settings
- name: Prepare to install plexmediaserver plugins
  block:
    - name: Download plexmediaserver plugins as zip files
      get_url:
        url: '{{ item }}'
        dest: '{{ plex.path }}/Plug-ins'
        mode: '777'
      with_items: '{{ multimedia_plexmediaserver_plugins }}'
      register: zip_files
      become: yes

    - name: Extract plexmediaserver plugins zip files into Plugins folder
      unarchive:
        src: '{{ item }}'
        dest: '{{ plex.path }}/Plug-ins'
        copy: no
      with_fileglob: '{{ plex.path }}/Plug-ins/*.zip'
      become: yes

    - name: Remove plexmediaserver plugins temporary files
      file:
        state: absent
        path: '{{ item }}'
      with_fileglob: '{{ plex.path }}/Plug-ins/*.zip'
      become: yes

- name: Restart plexmediaserver service
  service:
    name: plexmediaserver.service
    state: restarted
  become: yes
