- name: Create the destination path for the Transmission Settings
  file:
    path: '/var/lib/transmission/.config/transmission-daemon'
    state: directory
    recurse: yes
    mode: '777'
  become: yes

- name: Stop Transmission if it exists
  service:
    name: transmission.service
    state: stopped
    enabled: no
  become: yes
  ignore_errors: yes

- name: Apply Transmission Settings from Template
  template:
    src: var/lib/transmission/.config/transmission-daemon/settings.json.j2
    dest: /var/lib/transmission/.config/transmission-daemon/settings.json
  become: yes

- name: Ensure Transmission is up
  service:
    name: transmission.service
    state: started
    enabled: yes
  become: yes
